#pragma once

#include "Engine.h"

namespace Engine
{
	class CBaseAttributableItem;
	class CBaseViewModel;

	class CBaseWeapon : public IClientEntity
	{
	public:
		//[swap_lines]
		int				GetWeaponId();
		int				GetWeaponType();
		int				GetWeaponAmmo();
		int				GetZoomLevel();
		bool			GetWeaponReload();
		float			GetNextPrimaryAttack();

		CWeaponInfo*			GetWeaponInfo();
		CBaseAttributableItem*	GeteAttributableItem();

		const char*		GetName();
		//const char*		GetPrintName(); //don't need as it's never called!
		//[/swap_lines]
	};

	class CBaseAttributableItem : public IClientEntity
	{
	public:
		//[swap_lines]
		short*			GetItemDefinitionIndex();
		int*			GetItemIDHigh();
		int*			GetAccountID();
		int*			GetEntityQuality();
		int*			GetOriginalOwnerXuidLow();
		int*			GetOriginalOwnerXuidHigh();
		int*			GetFallbackPaintKit();
		float*			GetFallbackWear();
		int*			GetFallbackSeed();
		int*			GetFallbackStatTrak();
		CBaseViewModel*	GetViewModel();
		//[/swap_lines]
	};

	//CSWeaponType - 18th March 2020
	enum WEAPON_TYPE {
		WEAPON_TYPE_KNIFE = 0,
		WEAPON_TYPE_PISTOL,
		WEAPON_TYPE_SUBMACHINEGUN,
		WEAPON_TYPE_RIFLE,
		WEAPON_TYPE_SHOTGUN,
		WEAPON_TYPE_SNIPER,
		WEAPON_TYPE_MACHINEGUN,
		WEAPON_TYPE_C4,
		WEAPON_TYPE_PLACEHOLDER,
		WEAPON_TYPE_GRENADE,
		WEAPON_TYPE_UNKNOWN,
	};

	//1st January 2021
    //ItemDefinitionIndex - item_definition_index
	enum WEAPON_ID {
		//weapons
		WEAPON_DEAGLE = 1,
		WEAPON_ELITE, //Dual Berettas
		WEAPON_FIVESEVEN,
		WEAPON_GLOCK,
		WEAPON_AK47 = 7,
		WEAPON_AUG,
		WEAPON_AWP,
		WEAPON_FAMAS,
		WEAPON_G3SG1,
		WEAPON_GALILAR = 13,
		WEAPON_M249,
		WEAPON_M4A1 = 16,
		WEAPON_MAC10,
		WEAPON_P90 = 19,
		WEAPON_ZONE_REPULSOR, //co-op mission thingy
		WEAPON_MP5SD = 23,
		WEAPON_UMP45,
		WEAPON_XM1014,
		WEAPON_BIZON,
		WEAPON_MAG7,
		WEAPON_NEGEV,
		WEAPON_SAWEDOFF,
		WEAPON_TEC9,
		WEAPON_TASER,
		WEAPON_HKP2000, //P2000
		WEAPON_MP7,
		WEAPON_MP9,
		WEAPON_NOVA,
		WEAPON_P250,
		WEAPON_SHIELD, //ballistic shield
		WEAPON_SCAR20,
		WEAPON_SG556,
		WEAPON_SSG08,
		WEAPON_KNIFEGG, //Gold Knife
		WEAPON_KNIFE, //Default (CT) Knife
		WEAPON_FLASHBANG,
		WEAPON_HEGRENADE,
		WEAPON_SMOKEGRENADE,
		WEAPON_MOLOTOV,
		WEAPON_DECOY,
		WEAPON_INCGRENADE,
		WEAPON_C4,
		ITEM_KEVLAR, //body armour
		ITEM_ASSAULTSUIT, //helmet + body armour
		ITEM_HEAVYASSAULTSUIT, //special armour in co-op modes
		ITEM_NVG = 54, //night vision goggles
		ITEM_DEFUSER = 55, //bomb defuser in bomb map, hostage cutter in hostage maps
		ITEM_CUTTERS, //hostage cutter (for faster hostage taking) only
		WEAPON_HEALTHSHOT = 57,
		WEAPON_KNIFE_T = 59, //Default (T) Knife
		WEAPON_M4A1_SILENCER,
		WEAPON_USP_SILENCER,
		WEAPON_CZ75A = 63,
		WEAPON_REVOLVER,
		WEAPON_TAGRENADE = 68,
		WEAPON_FISTS,
		WEAPON_BREACHCHARGE,
		WEAPON_TABLET = 72,
		WEAPON_MELEE = 74,
		WEAPON_AXE,
		WEAPON_HAMMER,
		WEAPON_SPANNER = 78, //Wrench
		WEAPON_KNIFE_GHOST = 80, //Spectral Shiv
		WEAPON_FIREBOMB,
		WEAPON_DIVERSION,
		WEAPON_FRAG_GRENADE,
		WEAPON_SNOWBALL,
		WEAPON_BUMPMINE,
		WEAPON_BAYONET = 500, //Bayonet
		WEAPON_KNIFE_CSS = 503, //CSS Knife
		WEAPON_KNIFE_FLIP = 505, //Flip Knife
		WEAPON_KNIFE_GUT, //Gut Knife
		WEAPON_KNIFE_KARAMBIT, //Karambit
		WEAPON_KNIFE_M9_BAYONET, //M9 Bayonet
		WEAPON_KNIFE_TACTICAL, //Huntsman Knife
		WEAPON_KNIFE_FALCHION = 512, //Falchion Knife
		WEAPON_KNIFE_SURVIVAL_BOWIE = 514, //Bowie Knife
		WEAPON_KNIFE_BUTTERFLY, //Butterfly Knife
		WEAPON_KNIFE_PUSH, //Shadow Daggers
		WEAPON_KNIFE_CORD = 517, //Paracord Knife
		WEAPON_KNIFE_CANIS = 518, //Survival Knife
		WEAPON_KNIFE_URSUS = 519, //Ursus Knife
		WEAPON_KNIFE_GYPSY_JACKKNIFE, //Navaja Knife
		WEAPON_KNIFE_OUTDOOR = 521, //Nomad Knife
		WEAPON_KNIFE_STILETTO = 522, //Stiletto Knife
		WEAPON_KNIFE_WIDOWMAKER, //Talon Knife
		WEAPON_KNIFE_SKELETON = 525, //Skeleton Knife

		//gloves
		STUDDED_BLOODHOUND_GLOVES = 5027,
		T_GLOVES = 5028, //Default (T) Gloves
		CT_GLOVES = 5029, //Default (CT) Gloves
		SPORTY_GLOVES = 5030,
		SLICK_GLOVES = 5031,
		LEATHER_HANDWRAPS = 5032,
		MOTORCYCLE_GLOVES = 5033,
		SPECIALIST_GLOVES = 5034,
		STUDDED_HYDRA_GLOVES = 5035,
		STUDDED_BROKENFANG_GLOVES = 4725,

		//player models (agents)
		CUSTOMPLAYER_T_MAP_BASED = 5036,
		CUSTOMPLAYER_CT_MAP_BASED,
		CUSTOMPLAYER_TM_ANARCHIST,
		CUSTOMPLAYER_TM_ANARCHIST_VARIANTA,
		CUSTOMPLAYER_TM_ANARCHIST_VARIANTB,
		CUSTOMPLAYER_TM_ANARCHIST_VARIANTC,
		CUSTOMPLAYER_TM_ANARCHIST_VARIANTD,
		CUSTOMPLAYER_TM_PIRATE,
		CUSTOMPLAYER_TM_PIRATE_VARIANTA,
		CUSTOMPLAYER_TM_PIRATE_VARIANTB,
		CUSTOMPLAYER_TM_PIRATE_VARIANTC,
		CUSTOMPLAYER_TM_PIRATE_VARIANTD,
		CUSTOMPLAYER_TM_PROFESSIONAL,
		CUSTOMPLAYER_TM_PROFESSIONAL_VAR1,
		CUSTOMPLAYER_TM_PROFESSIONAL_VAR2,
		CUSTOMPLAYER_TM_PROFESSIONAL_VAR3,
		CUSTOMPLAYER_TM_PROFESSIONAL_VAR4,
		CUSTOMPLAYER_TM_SEPARATIST,
		CUSTOMPLAYER_TM_SEPARATIST_VARIANTA,
		CUSTOMPLAYER_TM_SEPARATIST_VARIANTB,
		CUSTOMPLAYER_TM_SEPARATIST_VARIANTC,
		CUSTOMPLAYER_TM_SEPARATIST_VARIANTD,
		CUSTOMPLAYER_CTM_GIGN,
		CUSTOMPLAYER_CTM_GIGN_VARIANTA,
		CUSTOMPLAYER_CTM_GIGN_VARIANTB,
		CUSTOMPLAYER_CTM_GIGN_VARIANTC,
		CUSTOMPLAYER_CTM_GIGN_VARIANTD,
		CUSTOMPLAYER_CTM_GSG9,
		CUSTOMPLAYER_CTM_GSG9_VARIANTA,
		CUSTOMPLAYER_CTM_GSG9_VARIANTB,
		CUSTOMPLAYER_CTM_GSG9_VARIANTC,
		CUSTOMPLAYER_CTM_GSG9_VARIANTD,
		CUSTOMPLAYER_CTM_IDF,
		CUSTOMPLAYER_CTM_IDF_VARIANTB,
		CUSTOMPLAYER_CTM_IDF_VARIANTC,
		CUSTOMPLAYER_CTM_IDF_VARIANTD,
		CUSTOMPLAYER_CTM_IDF_VARIANTE,
		CUSTOMPLAYER_CTM_IDF_VARIANTF,
		CUSTOMPLAYER_CTM_SWAT,
		CUSTOMPLAYER_CTM_SWAT_VARIANTA,
		CUSTOMPLAYER_CTM_SWAT_VARIANTB,
		CUSTOMPLAYER_CTM_SWAT_VARIANTC,
		CUSTOMPLAYER_CTM_SWAT_VARIANTD,
		CUSTOMPLAYER_CTM_SAS_VARIANTA,
		CUSTOMPLAYER_CTM_SAS_VARIANTB,
		CUSTOMPLAYER_CTM_SAS_VARIANTC,
		CUSTOMPLAYER_CTM_SAS_VARIANTD,
		CUSTOMPLAYER_CTM_ST6,
		CUSTOMPLAYER_CTM_ST6_VARIANTA,
		CUSTOMPLAYER_CTM_ST6_VARIANTB,
		CUSTOMPLAYER_CTM_ST6_VARIANTC,
		CUSTOMPLAYER_CTM_ST6_VARIANTD,
		CUSTOMPLAYER_TM_BALKAN_VARIANTE,
		CUSTOMPLAYER_TM_BALKAN_VARIANTA,
		CUSTOMPLAYER_TM_BALKAN_VARIANTB,
		CUSTOMPLAYER_TM_BALKAN_VARIANTC,
		CUSTOMPLAYER_TM_BALKAN_VARIANTD,
		CUSTOMPLAYER_TM_JUMPSUIT_VARIANTA,
		CUSTOMPLAYER_TM_JUMPSUIT_VARIANTB,
		CUSTOMPLAYER_TM_JUMPSUIT_VARIANTC,
		CUSTOMPLAYER_TM_PHOENIX_HEAVY,
		CUSTOMPLAYER_CTM_HEAVY,
		CUSTOMPLAYER_TM_LEET_VARIANTA = 5100,
		CUSTOMPLAYER_TM_LEET_VARIANTB,
		CUSTOMPLAYER_TM_LEET_VARIANTC,
		CUSTOMPLAYER_TM_LEET_VARIANTD,
		CUSTOMPLAYER_TM_LEET_VARIANTE,
		CUSTOMPLAYER_TM_LEET_VARIANTG,
		CUSTOMPLAYER_TM_LEET_VARIANTH,
		CUSTOMPLAYER_TM_LEET_VARIANTI,
		CUSTOMPLAYER_TM_LEET_VARIANTF,
		CUSTOMPLAYER_TM_PHOENIX = 5200,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTA,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTB,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTC,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTD,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTH,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTF,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTG,
		CUSTOMPLAYER_TM_PHOENIX_VARIANTI,
		CUSTOMPLAYER_CTM_FBI = 5300,
		CUSTOMPLAYER_CTM_FBI_VARIANTA,
		CUSTOMPLAYER_CTM_FBI_VARIANTC,
		CUSTOMPLAYER_CTM_FBI_VARIANTD,
		CUSTOMPLAYER_CTM_FBI_VARIANTE,
		CUSTOMPLAYER_CTM_FBI_VARIANTF,
		CUSTOMPLAYER_CTM_FBI_VARIANTG,
		CUSTOMPLAYER_CTM_FBI_VARIANTH,
		CUSTOMPLAYER_CTM_FBI_VARIANTB,
		CUSTOMPLAYER_CTM_ST6_VARIANTK = 5400,
		CUSTOMPLAYER_CTM_ST6_VARIANTE,
		CUSTOMPLAYER_CTM_ST6_VARIANTG,
		CUSTOMPLAYER_CTM_ST6_VARIANTM,
		CUSTOMPLAYER_CTM_ST6_VARIANTI,
		CUSTOMPLAYER_CTM_ST6_VARIANTJ = 4619,
		CUSTOMPLAYER_CTM_ST6_VARIANTL = 4680,
		CUSTOMPLAYER_TM_BALKAN_VARIANTF = 5500,
		CUSTOMPLAYER_TM_BALKAN_VARIANTI,
		CUSTOMPLAYER_TM_BALKAN_VARIANTG,
		CUSTOMPLAYER_TM_BALKAN_VARIANTJ,
		CUSTOMPLAYER_TM_BALKAN_VARIANTH,
		CUSTOMPLAYER_TM_BALKAN_VARIANTK = 4718,
		CUSTOMPLAYER_TM_BALKAN_VARIANTL = 5505,
		CUSTOMPLAYER_CTM_SAS = 5600,
		CUSTOMPLAYER_CTM_SAS_VARIANTF,
		CUSTOMPLAYER_CTM_SWAT_VARIANTE = 4711,
		CUSTOMPLAYER_CTM_SWAT_VARIANTF,
		CUSTOMPLAYER_CTM_SWAT_VARIANTG,
		CUSTOMPLAYER_CTM_SWAT_VARIANTH,
		CUSTOMPLAYER_CTM_SWAT_VARIANTI,
		CUSTOMPLAYER_CTM_SWAT_VARIANTJ,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARF = 4726,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARF1 = 4733,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARF2,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARF3,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARF4,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARG = 4727,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARH,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARI = 4732,
		CUSTOMPLAYER_TM_PROFESSIONAL_VARJ = 4730
	};
}
	